import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Spline from "@splinetool/react-spline";
import { Grid, GridItem } from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid templateColumns="repeat(2, 1fr)" gap={6}>
        <GridItem w="100%">
          <main className={styles.main}>
            <h1 className={styles.title}>
              Nur <a href="#">Ikhwanudin</a>
            </h1>

            <p className={styles.description}>
              <code className={styles.code}>Fullstack Web Developer</code>
            </p>
          </main>
        </GridItem>
        <GridItem w="100%">
          <Spline scene="https://prod.spline.design/2uQVGT14nDHVknZt/scene.splinecode" />
        </GridItem>
      </Grid>
    </div>
  );
}
